[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions."push-dispatcher"]
  schedule = "*/5 * * * *"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
